//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANEPROJE_DENEMELER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVERAGE_SCORE
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public decimal AverageStar { get; set; }
        public int VotePiece { get; set; }
    
        public virtual TBLKİTAPLAR TBLKİTAPLAR { get; set; }
    }
}
