//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANEPROJE_DENEMELER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUSER()
        {
            this.TBLSECİLEN_KİTAPLAR = new HashSet<TBLSECİLEN_KİTAPLAR>();
            this.TBLAVERAGE_NOTE = new HashSet<TBLAVERAGE_NOTE>();
        }
    
        public int UserID { get; set; }
        public short YetkiID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string TC { get; set; }
        public string Fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSECİLEN_KİTAPLAR> TBLSECİLEN_KİTAPLAR { get; set; }
        public virtual TBLYETKİLER TBLYETKİLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAVERAGE_NOTE> TBLAVERAGE_NOTE { get; set; }
    }
}
